### ISSUE TITLE
AppImage no longer available in releases

### ISSUE THREAD

**Issue by m-kuhn** [linuxdeploy/linuxdeploy-plugin-appimage#21]
Thank you for this excellent tool which we use to regularly build portable linux executables for our app.

Since recently, the release seems to be gone in the url we've been using before and I cannot find a new one

> https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage:
> 2022-07-16 06:07:59 ERROR 404: Not Found.

Is there another (stable) url where this can be downloaded?

**Comment by m-kuhn** [comment]
Could be related to a failed CI run here https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/actions/runs/2680333483

**Comment by m-kuhn** [comment]
One further note related to this, it would be a nice idea to create a release with a stable tag next to the moving target [continuous](https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/tag/continuous).

**Comment by TheAssassin** [comment]
I manually deleted the release last night while running the action manually to have a new upload within a few minutes. Unfortunately, it turned out the AppImageKit pipeline had not finished yet, but I needed to include the new release. I should have let the pipeline here run and build binaries using the old release to avoid downtimes.

Most users do not use the AppImage plugin directly but use the version embedded in linuxdeploy, so I didn't really think of this kind of impact on other users. Sorry for the downtime. Fixing this right now.

**Comment by TheAssassin** [comment]
By the way, there is a discussion going on in the background whether to provide some sort of releases as "stable points" which can be used more reliably by users.

**Comment by TheAssassin** [comment]
Fixed: https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/tag/continuous

**Comment by m-kuhn** [comment]
Thank you for the quick fix

> By the way, there is a discussion going on in the background whether to provide some sort of releases as "stable points" which can be used more reliably by users.

That would be much appreciated!
