### ISSUE TITLE
glibc requirements for aarch64 support

### ISSUE THREAD

**Issue by rmartin16** [linuxdeploy/linuxdeploy-plugin-appimage#28]
Thanks for creating [versions for arm](https://github.com/linuxdeploy/linuxdeploy/issues/175#issuecomment-1841948736).

We've been targeting glibc 2.17 for x86 for a while....but the aarch64 version is seemingly looking for at least 2.25:
```
[appimage/stderr] appimagetool: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/appimage_extracted_a6dc6e7d0c1514c8714921f9e2e39fc1/plugins/linuxdeploy-plugin-appimage/appimagetool-prefix/usr/lib/libgcrypt.so.20)
```

Intentional? Otherwise?

**Comment by TheAssassin** [comment]
That's expected behavior. appimagetool is built on a more recent distribution as CentOS 7 had never shipped ARM versions. Feel free to open an issue over at https://github.com/AppImage/AppImageKit. We recently refactored appimagetool out of this repository and may be able to provide statically linked versions of it which linuxdeploy-plugin-appimage can use.
